services:
  app:
    build: .
    container_name: storebox-app
    env_file:  .env
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_SQL_INIT_MODE=${SPRING_SQL_INIT_MODE}
      - SERVER_PORT=${SERVER_PORT}
      - WEBSITE_URL=${WEBSITE_URL}
    ports:
      - "${SERVER_PORT:-8080}:8080"
    volumes:
      - ./logs:/app/logs
